# Librerías que se van necesitando -- No todas se han usado al final
library(ggplot2)
library(Hmisc)
library(mice)
library(VIM)
library(FSelector)
library(mlbench)
library(lattice)
library(caret)
library(e1071)
library(randomForest)
library(NoiseFiltersR)
library(Rlof)
library(plyr)
library(dplyr)
library(pROC)
